spring:
  application:
    name: cart-sync-mission
  datasource:
    url: jdbc:h2:mem:cart-sync;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
